### ISSUE TITLE
trying to delete folders that aren't empty raises an error

### ISSUE THREAD

**Issue by tmaybe** [chimecms/chime#119]
Trying to delete a folder that contains files in the file explorer (using the trash can icon) raises this error: `OSError: [Errno 66] Directory not empty`

We should be able to delete non-empty folders. Maybe with a confirmation dialog?

**Comment by phae** [comment]
Yeah :+1: to the ability to delete folders with stuff in. #81 asks that we warn before deleting things, anyway.

**Comment by migurski** [comment]
There is no longer a delete button on folders, so this bug is moot.
