### ISSUE TITLE
Hitting "preview" should also do a save action

### ISSUE THREAD

**Issue by phae** [chimecms/chime#181]

**Comment by wpietri** [comment]
I have this apparently working in the markdown-user-test-1 branch but not deployed, as I don't want to risk blowing up the user test. We should figure out whether we want to merge this code back to master.

**Comment by migurski** [comment]
Checked on form target to new windows, and this small app works as-expected:

```
from flask import Flask, redirect, request

app = Flask(__name__)

@app.route('/')
def index():
    ''' Show a form that sends a POST request /post in a new window '''
    return '<form method="POST" action="/post" target="_blank"><input type="submit"></form>'

@app.route('/post', methods=['POST'])
def post():
    ''' Process the POST request and redirect the client to GET /posted '''
    return redirect('/posted', code=303)

@app.route('/posted')
def posted():
    ''' All is well. '''
    return 'Yay'

app.run(debug=True)
```

**Comment by phae** [comment]
In terms of a testing matrix, I would like to use the matrix on this page: https://www.gov.uk/service-manual/user-centred-design/browsers-and-devices.html MINUS IE6 and IE7.  So for desktop browsers: IE8+ get a fully-functional whizzy JS version and everything should be tested there. Safari goes 1 version back + current version (because it's tied to OS) and the others are all current.  Mobile just as in the grid.

**Comment by wpietri** [comment]
Ok. Frances and I looked at the available options: https://www.browserstack.com/list-of-browsers-and-platforms?product=live

I believe the conclusion is to test on:
* Desktop
  * Windows XP
    * IE 8
    * Firefox latest
    * Chrome latest
  * Windows 7
    * IE 8, 9, 10, 11
    * Firefox latest
    * Chrome latest
  * Windows 8.1
    * IE 11
    * Firefox latest
    * Chrome latest
  * Windows 10
    * IE 11
    * Firefox latest
    * Chrome latest
* Mobile
  * IOS 6, 7, 8 on one phone each
  * Android 4.1-4.4, one device each

Which is a total of 21 targets.

**Comment by phae** [comment]
+ #417 will help the non-JS route in terms of getting back to stuff.

**Comment by phae** [comment]
Blocked by #321
