### ISSUE TITLE
Refactor UI with new design

### ISSUE THREAD

**Issue by phae** [chimecms/chime#215]
Add some basic nav to get back to browse / task setup, too

**Comment by tmaybe** [comment]
screenshot of new design pls.

**Comment by phae** [comment]
--^ @norrishung

**Comment by norrishung** [comment]
![screen shot 2015-05-14 at 3 48 48 pm](https://cloud.githubusercontent.com/assets/606439/7643731/cd0f501a-fa50-11e4-8c38-d4fbe4cc35cb.png)
![screen shot 2015-05-14 at 3 49 03 pm](https://cloud.githubusercontent.com/assets/606439/7643730/cd0e81e4-fa50-11e4-9e6a-5c49a3e4bc9b.png)

**Comment by phae** [comment]
Just to be super crystal clear, this ticket is just for applying CSS to pull the layout into this shape - the screenshots above have some features in it that are in the bootcamp 'nice to have' list and are reflected in other tickets and aren't to be covered in this one.  This ticket could be summarised as "make it the grey and a full bleed layout"
