### ISSUE TITLE
Preview sometimes doesn't work because the jekyll build isn't finished.

### ISSUE THREAD

**Issue by phae** [chimecms/chime#236]
We probably need to block on preview until the build has finished.

**Comment by wpietri** [comment]
Looking at the code, it  appears that we block until the build has finished, and have for quite a while. Can anybody help me reproduce this?

**Comment by migurski** [comment]
I haven’t actually experienced this behavior myself.

**Comment by tmaybe** [comment]
I haven't either.

**Comment by phae** [comment]
If it's no longer reproducible, that's good. This is a pretty old ticket. :)
