### ISSUE TITLE
Add GPL licensing to chime-starter repo.

### ISSUE THREAD

**Issue by norrishung** [chimecms/chime#262]

**Comment by norrishung** [comment]
Added the license that every other project at CfA uses instead. (Including chime).

**Comment by migurski** [comment]
Possible quibble: GPL might not be the best license for site content, since it’s perhaps more of a creative work than a software product. CC-BY-SA may be more appropriate?

**Comment by norrishung** [comment]
This makes much more sense. Thanks Mike!
