### ISSUE TITLE
Setup email address for support@chimecms.org

### ISSUE THREAD

**Issue by phae** [chimecms/chime#290]

**Comment by phae** [comment]
Add this address to the 404 page, too. cc @norris

**Comment by migurski** [comment]
Where do we want this to go? Do we want it to forward?

**Comment by migurski** [comment]
@wpietri suggests that chime@codeforamerica.org is appropriate, so I have verified that it’s set up as a forwarding address to myself, Cyd, Tomas, Frances, William, and Norris.
