### ISSUE TITLE
Buy burner phone and add number to error page

### ISSUE THREAD

**Issue by phae** [chimecms/chime#291]

**Comment by bsmithgall** [comment]
there's also [an app for that](http://www.burnerapp.com/)

**Comment by phae** [comment]
We want a physical bat phone, but that's pretty cool too. :)

**Comment by bsmithgall** [comment]
:+1: :phone:

**Comment by migurski** [comment]
Our Chime Phone number is 415-323-9728. I’ve set it up with chimey ringtones.
