### ISSUE TITLE
Springfield site displays incorrect task owners

### ISSUE THREAD

**Issue by migurski** [chimecms/chime#295]
On http://springfield-admin.chimecms.org, I see the incorrect `ubuntu@` email address displayed:

![badchime](https://cloud.githubusercontent.com/assets/58730/8415604/e7013e0c-1e54-11e5-8c87-ab4f9196eedf.png)

But in `/var/opt/chime-site`, the git commit information for the start of the task looks fine:

```
commit 0fdac42b53d35bbb22b2dca8e82958748f752f52
Author:  <mike@codeforamerica.org>
Date:   Mon Jun 29 18:41:53 2015 +0000

    The "Writing some words" activity was started
    
    Created task metadata file "_task.yml"
    Set author_email to mike@codeforamerica.org
    Set task_description to Writing some words
    Set task_beneficiary to content consumers

diff --git a/_task.yml b/_task.yml
new file mode 100644
index 0000000..3238f10
--- /dev/null
+++ b/_task.yml
@@ -0,0 +1,6 @@
+"author_email": |-
+  mike@codeforamerica.org
+"task_beneficiary": |-
+  content consumers
+"task_description": |-
+  Writing some words
```

**Comment by norrishung** [comment]
Currently, it should be displaying the last editor of that activity, not the author. I felt that showing the last editor paints a more accurate/current picture of that activity than who created the activity. I'd be happy to discuss if people have a different opinion about that.

Also not sure if the ubuntu@ email address is actually the last editor. That could still be a bug.

**Comment by tmaybe** [comment]
As soon as you make an edit, the information is correct. So the bug only happens with newly created activities with no changes made.

**Comment by migurski** [comment]
The ubuntu@ email address should never be seen, so it’s definitely a bug.
