### ISSUE TITLE
Missing branch should not redirect

### ISSUE THREAD

**Issue by migurski** [chimecms/chime#301]
Currently, http://springfield-admin.chimecms.org/tree/5a743f4/ redirects to http://springfield-admin.chimecms.org/ which shows the message “There is no 5a743f4 branch!” I got that URL from Slack, so the branch did exist in the past.

It would be better for this to not redirect, and instead tell you that the branch doesn’t exist on the page you are looking at. The redirect adds a potential point of confusion, especially if we’re going to be helping people and asking them what URL they are viewing.

**Comment by tmaybe** [comment]
What should be displayed on the page? If the branch no longer exists, there's no content to flesh out a template. Are you saying it should render the index page but not change the URL in the location bar? What should we show on a completely made-up URL? like http://springfield-admin.chimecms.org/tree/nothing-to-see-here/

**Comment by migurski** [comment]
Just a "nothing here" message or similar, instead of a small message flashed after redirect.

**Comment by migurski** [comment]
If we have a way of differentiating between old branches and made-up URLs there might be something interesting to do, but generally I just want to make sure we show a useful thing without bouncing someone elsewhere.

**Comment by tmaybe** [comment]
I can use one of the error page designs from #283 for this

**Comment by migurski** [comment]
:+1:
