### ISSUE TITLE
Internal error when saving a new article

### ISSUE THREAD

**Issue by migurski** [chimecms/chime#321]
Tried to save a [new article](http://springfield-admin.chimecms.org/tree/74b5d90/save/categories/parks-recreation/aquatics/mount-splashmore/index.markdown), got an internal error.

This is the likely corresponding error via SNS:

```
2015-07-02 21:39:47,241 - chime.view_functions - ERROR - Out of date SHA: c1fcb05d39fbe80287ee229bd04761254030dcbd
Traceback (most recent call last):
 File "/home/ubuntu/chime/chime/view_functions.py", line 432, in decorated_function
   return route_function(*args, **kwargs)
 File "/home/ubuntu/chime/chime/view_functions.py", line 464, in decorated_function
   return route_function(*args, **kwargs)
 File "/home/ubuntu/chime/chime/view_functions.py", line 520, in decorated_function
   response = route_function(*args, **kwargs)
 File "/home/ubuntu/chime/chime/views.py", line 775, in branch_save
   raise Exception('Out of date SHA: %s' % request.form.get('hexsha'))
Exception: Out of date SHA: c1fcb05d39fbe80287ee229bd04761254030dcbd

Request info:
<Request 'http://springfield-admin.chimecms.org/tree/74b5d90/save/categories/parks-recreation/aquatics/mount-splashmore/index.markdown' [POST]>
```

**Comment by migurski** [comment]
I went back, re-saved, and it worked.

**Comment by tmaybe** [comment]
I bet this is because multiple ppl. are working on the same activity/branch? Between the time you started your edit (at which time the sha is generated and embedded in the form) and when you submitted it, someone else submitted their own edit, which made yours out of date.

**Comment by tmaybe** [comment]
Note that this currently happens if another person edits **any file** in your activity while you're editing your file, it doesn't have to be the same file.

**Comment by migurski** [comment]
Any edit would make the commit sha out-of-date, so it makes sense.

**Comment by migurski** [comment]
(still a bug but that’s what’s happening)
