### ISSUE TITLE
Provide clearer summary of activity state.

### ISSUE THREAD

**Issue by migurski** [chimecms/chime#325]
It’s hard to tell what to review when looking at an activity.

**Comment by phae** [comment]
#310 relates.

**Comment by norrishung** [comment]
Umbrella task for:

- #310: Links in history items
- #336: Activity Progress Bar
- #350: Summary of Changed Files

**Comment by norrishung** [comment]
Proposed design for activity overview page that includes activity progress bar and summary.

![screen shot 2015-07-09 at 11 39 20 am](https://cloud.githubusercontent.com/assets/606439/8603809/5adf8734-262f-11e5-89ca-435ec4b03e33.png)
![screen shot 2015-07-09 at 11 39 14 am](https://cloud.githubusercontent.com/assets/606439/8603810/5adff4bc-262f-11e5-9acf-4d75d99ddf4e.png)
