### ISSUE TITLE
Activity name field should be required

### ISSUE THREAD

**Issue by cydharrell** [chimecms/chime#334]
The system allows you to create an activity with a blank name, resulting in some weird appearances: 
![screen shot 2015-07-02 at 3 14 49 pm](https://cloud.githubusercontent.com/assets/5133498/8489126/39b00fe6-20cd-11e5-9d91-ff9f60f3f8ed.png)

**Comment by phae** [comment]
+1 

Happy to have "for [ ___ ]" field as optional and mark it as such, too.

**Comment by colleencotter** [comment]
![screen shot 2015-07-02 at 3 14 50 pm](https://cloud.githubusercontent.com/assets/12877190/8489184/9d0eb72c-20cd-11e5-98ed-91fbe9b822f4.png)
