### ISSUE TITLE
better error when a task has been deleted or completed

### ISSUE THREAD

**Issue by cydharrell** [chimecms/chime#337]
"there is no 7ee67c branch" is Github lingo, it should ideally say something like "couldn't save because this task has already been published" 
![screen shot 2015-07-02 at 3 26 20 pm](https://cloud.githubusercontent.com/assets/5133498/8489295/e297929a-20ce-11e5-824f-32fc6ad6a0c1.png)

**Comment by tmaybe** [comment]
See #301
