### ISSUE TITLE
Use a different set of character when making branch names

### ISSUE THREAD

**Issue by migurski** [chimecms/chime#340]
Generated branch names look uncannily like Git SHA strings, since they use the same 0–F character set [in `make_branch_sha()`](https://github.com/chimecms/chime/blob/890e94ab7be05325259504610a7ba462c31a395f/chime/repo_functions.py#L315). 

Try mapping them through this dictionary to transpose to g–v:

    dict(zip('0123456789abcdef', 'ghijklmnopqrstuv'))

**Comment by tmaybe** [comment]
it'd be easier to do #207 now that we can slugify things...

**Comment by tmaybe** [comment]
one problem with this is that it'd be a lot easier to unintentionally spell words, like _hognuts_, _gunshot_, _gnomish_, _nostril_, _moshing_, _liquors_, _nitrous_, _turmoil_, _vomitus_, and _milksop_. Assuming we stick with the 7-letter limit. Maybe we can keep the numbers and just swap out some letters?

**Comment by migurski** [comment]
Getting rid of vowels can help. Main thing here is to visually distinguish branch names from commit SHAs when peeking under the hood.
