### ISSUE TITLE
Fix Error Page Wording

### ISSUE THREAD

**Issue by norrishung** [chimecms/chime#359]

**Comment by tmaybe** [comment]
Also, if you propose a better way to show which files are conflicting in a merge conflict, I can work with you to implement it.

**Comment by phae** [comment]
Remember to add email and bat phone!

**Comment by norrishung** [comment]
Hey, bat phone and email are already in there (chime instances just need to be configured with them). Did a little bit of rewording and also fixing of design for readability.

@tomas, can you help to make sure we have the right parameters for the merge table?

**Comment by norrishung** [comment]
<img width="1279" alt="screen shot 2015-07-24 at 12 16 27 pm" src="https://cloud.githubusercontent.com/assets/606439/8882707/ffa39f4c-31fd-11e5-8a5a-6ff13d7e7a6d.png">
<img width="1276" alt="screen shot 2015-07-24 at 12 15 38 pm" src="https://cloud.githubusercontent.com/assets/606439/8882708/ffb332fe-31fd-11e5-82ad-d7fb8f5e9b0d.png">
<img width="1276" alt="screen shot 2015-07-24 at 12 16 48 pm" src="https://cloud.githubusercontent.com/assets/606439/8882709/ffbe808c-31fd-11e5-8733-e34c3cd783f9.png">

**Comment by migurski** [comment]
Taking this over to implement in code.

**Comment by migurski** [comment]
Nevermind, leaving this for Tomas. :)
