### ISSUE TITLE
Decide how authentication should work for boot camp

### ISSUE THREAD

**Issue by migurski** [chimecms/chime#377]
@phae and I need to figure this out in time for next week.

**Comment by phae** [comment]
Do you mean ditching the spreadsheet thing or just populating them with values?

**Comment by migurski** [comment]
Either or both. It’s not 100% clear to me where the authentication data is coming from now, and where it should come from next week. Let’s have a 20min deepdive about this to levelset.

**Comment by phae** [comment]
:+1:

**Comment by migurski** [comment]
Picking through the current code, looks like `data/authentication.csv` is the default value. Via [`view_functions.get_auth_data_file()`](https://github.com/chimecms/chime/blob/01bac2fe3936213ca32ecf927765d09c1bfda61f/chime/view_functions.py#L332), that leads to [`chime/data/authentication.csv`](https://github.com/chimecms/chime/blob/679ee6ba85dbcd5aa816fbfd57aa18c3dfb8bd34/chime/data/authentication.csv). Changing the values there has the correct effect.

**Comment by migurski** [comment]
Our pre-@wpietri intent was that [this master spreadsheet](https://docs.google.com/spreadsheets/d/12jUfaRBd-CU1_6BGeLFG1_qoi7Fw_vRC_SXv36eDzM0/edit#gid=721924872) would be cloned for users, and that it would be publicly accessible as a CSV for site owners to edit. It _should work_ to specify its public URL.

**Comment by migurski** [comment]
For this to work for real, we’ll want to make sure Chime is not attempting to make requests to a remote CSV on every single request, just the one where someone logs in.

**Comment by phae** [comment]
https://drive.google.com/open?id=1urJ6bEI8Xwsc_BnvdmR8PFKjrJDYemCbaAXYJPr5iIw
https://drive.google.com/open?id=1hy8IK56FfGLOFMYO0oRUtM2GNIy1yLYCLvf-yDYBB9E
https://drive.google.com/open?id=1XpdavDAndeot2dFdCRHoBZeeslCZH5Mp4NRfKibpPRE
https://drive.google.com/open?id=1jfU2b1S1hFBHtSTlizKvvsXn3ww5hxu7ORKFtwDvuLw
https://drive.google.com/open?id=1Qj2gQ4zDTGnS2RlXAjU26F60iLuv6FqdBF6ayRyzHjg

**Comment by migurski** [comment]
This was answered in https://github.com/chimecms/chimechef/issues/3
