### ISSUE TITLE
Stop reporting 404s as errors

### ISSUE THREAD

**Issue by migurski** [chimecms/chime#383]

**Comment by tmaybe** [comment]
Does this mean don't log 404 errors so they aren't emailed to support? If so, should just have to check `e.code` in `view_functions/log_application_errors()` and only log if it's not `404`.

**Comment by wpietri** [comment]
That sounds great. Per @migurski's suggestion, I suspect all 400-class errors can be ignored, but it's the 404s that are making me error-blind now.

**Comment by migurski** [comment]
Yeah, only things in the [5XX range](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5) should generate email.

5XX = We Fucked Up / 4XX = You Fucked Up.
