### ISSUE TITLE
clicking submit buttons multiple times results in unwanted multiple submissions

### ISSUE THREAD

**Issue by tmaybe** [chimecms/chime#468]
You can create 10 identically-named activities, etc.

**Comment by norrishung** [comment]
Do you have any ideas on how to address this? Should just have some progressive enhanced js that allows us to disable submit buttons after they've been clicked and swaps out text with a loading symbol?

**Comment by norrishung** [comment]
![screen shot 2015-08-19 at 5 31 27 pm](https://cloud.githubusercontent.com/assets/606439/9372842/46d3e4f4-4698-11e5-97bf-d88f88831e54.png)

**Comment by tmaybe** [comment]
maybe that + some work on the backend to id multiple unwanted submissions

**Comment by tmaybe** [comment]
Not ready to merge. @norrishung is:

- [ ] restyling the 'button clicked' state

first.

**Comment by norrishung** [comment]
http://fontastic.me/ I'm considering using this to generate a custom icon font for us because:

1. Remove icons we don't use to make chime more performant.
2. Ability to add custom icons.
3. Icon fonts have a lot of advantages in terms of browser compatibility and resource loading performance.

**Comment by norrishung** [comment]
Hmm also just found this. Apparently, this is a huge issue.

https://github.com/FortAwesome/Font-Awesome/issues/671#issuecomment-65381998
