### ISSUE TITLE
Saving an article from the article edit screen with non-roman text in the title raises a UnicodeDecodeError

### ISSUE THREAD

**Issue by tmaybe** [chimecms/chime#493]
To reproduce, open any article, replace the title text with 快速狐狸 and click save.

**Comment by tmaybe** [comment]
Caveat: this was happening with GitPython 1.0.1 installed; doesn't happen with GitPython 0.3.2.RC1

**Comment by phae** [comment]
Is this our bug or gitpython's?

**Comment by tmaybe** [comment]
It will be fixed when we merge PR #514

**Comment by tmaybe** [comment]
closed by #514
