### ISSUE TITLE
Make it possible to describe an activity at the end of the change

### ISSUE THREAD

**Issue by phae** [chimecms/chime#515]
After you hit save, ask to describe the activity (instead of at first)

**Comment by norrishung** [comment]
Finished with the design portion of this. Off to @tmaybe to finish the implementation. Mainly:
    1. Actually allow for creation of activity without naming it.
    2. Ability to rename activity task_description from review modal and activity overview page.
    3. Pluralizing of #files changed in the activity bar and review modal.

List of front-end changes made:
    1. changed activity dropdown to activity bar
    2. allow for review behavior to happen in modal
    3. changed activity summary ui
    4. allow for activity to be renamed from modal and within activity overview page
    	- needs backend
    6. allow for activity to be deleted within activity page
    7. show how many files have changed within an activity across interface
    	- needs pluralizing
    8. condensed all activity actions at the top of page
