### ISSUE TITLE
Display recently merged activities at bottom of activity page

### ISSUE THREAD

**Issue by phae** [chimecms/chime#519]
Doesn't need to be all of them - last 10 would do.

**Comment by phae** [comment]
This is an enhancement to #517

**Comment by tmaybe** [comment]
as per discussion the morning of 9/8/2015, we're going to implement this in stages:

- [ ] Published activities are listed on the activity list page, but you can't click into them
- [ ] You can click into the activity and see its overview page (which may include comments or other commits from activities that were going on concurrently)
- [ ] The published activity's overview page shows only its own comments and commits

**Comment by tmaybe** [comment]
part 2/3 is done as of d78da2eea9907ef0c126ad24ef7405d96285b571!

**Comment by tmaybe** [comment]
This was closed by #538
